### ISSUE TITLE
Installation using Git not working

### ISSUE THREAD

**Issue by vednolacni** [lioneil/obsidian-es-theme-retropie#1]
![Screenshot 2024-08-01 at 18 14 13](https://github.com/user-attachments/assets/38dc4fe7-bec0-4284-a625-327862311095)

**Comment by lioneil** [comment]
Your first `cd` command did not complete successfully.
You'll have to create the folders.
Try:
```bash
mkdir -p ~/.emulationstation/themes/
```
Then proceed with the rest of the commands.

Note that the second command `git clone` was successful, so maybe you can just move that folder to the newly created one.
